# -*- coding: utf-8 -*-
"""chapter3_exercise_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N45UIHMzDW1gGBUD6wBYJtk6bTv7KGL2
"""

guests=["Teena","Megna","Sandhra"]

name=guests[0].title()
print(name+",please come to dinner")

name=guests[1].title()
print(name+",please come to dinner")

name=guests[2].title()
print(name+",please come to dinner")