# -*- coding: utf-8 -*-
"""chapter3_exercise_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3vLmNcMg8APnij-pQs70WJQep4GXNqK
"""

motorcycle=["Honda","Royal_Enfield","RX100","suzuki","Harley"]
print(motorcycle)

statements="I would like to own a "

print(statements,motorcycle[0]+" motorcycle")

print(statements,motorcycle[1]+" motorcycle")

print(statements,motorcycle[2]+" motorcycle")

print(statements,motorcycle[3]+" motorcycle")

print(statements,motorcycle[4]+" motorcycle")