# -*- coding: utf-8 -*-
"""chapter3_exercise_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/180YuJOLljNVywkw52D2382eHf2G8_Jyw
"""

guests=["Teena","Megna","Mindy"]
name = guests[0].title()
print( name + ", please come to dinner.")
name = guests[1].title()
print( name + ", please come to dinner.")
name = guests[2].title()
print( name + ", please come to dinner.")

print("\nSorry, we can only invite two people to dinner, because of the new table won`t arrive on time.")

name = guests.pop()
print("Sorry, " + name.title() + " there's no room at the table.")

name = guests[0].title()
print(name + ", please come to dinner.")

name = guests[2].title()
print(name + ", please come to dinner.")

del(guests[0])
del(guests[0])

print(guests)