# -*- coding: utf-8 -*-
"""chapter3_exercise_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WxmaSDnGae1nYKhBcG4xglMUHbm5JhoE
"""

names=["Harsha","Hiba","Niptha","Izza","Wafa"]
message="you`re beautifull"

print(message,names[0])

print(message,names[1])

print(message,names[2])

print(message,names[3])

print(message,names[4])