# -*- coding: utf-8 -*-
"""chapter3_exercise_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYwhCZitZkJ6399KVmugZlyd7NhwwhvM
"""

guests=["Teena","Megna","Sandhra"]

name=guests[0].title()
print(name+",please come to dinner")
name=guests[1].title()
print(name+",please come to dinner")
name=guests[2].title()
print(name+",please come to dinner")

name = guests[2].title()
print("\nSorry, " + name + " can't make it to dinner.")

del(guests[2])
guests.insert(2, 'Mindy')

name = guests[0].title()
print( name + ", please come to dinner.")
name = guests[1].title()
print( name + ", please come to dinner.")
name = guests[2].title()
print( name + ", please come to dinner.")