# -*- coding: utf-8 -*-
"""chapter3_exercise_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AeCS10BNJUXHGaf0rRsE0b1QwEqgBkOy
"""

names=["Harsha","Hiba","Niptha","Izza","Wafa"]

print(names[0])

print(names[1])

print(names[2])

print(names[3])

print(names[4])